Repository scalar-labs/scalar-ist, pull requests merged in 2022-08, with the labels that each got.

#8 Add support for Scalar DL 3.5.2 and Auditor
  contracts_and_functions/.gitignore
  contracts_and_functions/build.gradle
  contracts_and_functions/gradle/wrapper/gradle-wrapper.jar
  contracts_and_functions/gradle/wrapper/gradle-wrapper.properties
  contracts_and_functions/gradlew
  contracts_and_functions/gradlew.bat
  contracts_and_functions/src/test/java/com/scalar/ist/tools/ContractUtil.java
  contracts_and_functions/src/test/java/com/scalar/ist/tools/Deploy.java
  tools/deploy_tool/.gitignore
  tools/deploy_tool/build.gradle
  tools/deploy_tool/gradle/wrapper/gradle-wrapper.jar
  tools/deploy_tool/gradle/wrapper/gradle-wrapper.properties
  tools/deploy_tool/gradlew
  tools/deploy_tool/gradlew.bat
  tools/deploy_tool/src/main/java/com/scalar/ist/tools/ContractUtil.java
  tools/deploy_tool/src/main/java/com/scalar/ist/tools/Deploy.java
Labels: enhancement

#9 Update to Scalar DL sdk 3.5.3
  contracts_and_functions/build.gradle
  tools/deploy_tool/build.gradle
Labels: enhancement

#10 Use Scalar JRE8 base image
  ist-loader/Dockerfile
Labels: enhancement

#11 Fix docker login for release
  .github/workflows/release.yml
Labels: bug

#12 Upgrade scalardb-schema-loader 3.6.0
  ist-schema-loader/Dockerfile
Labels: bug

#15 Fix order of user profile commands and remove $
  docs/how_to_use.md
Labels: documentation

#14 Add missing category_of_data column in data_set_schema table
  ist-schema-loader/schema/ist.transaction.json
Labels: bug

#13 Add script to run all contracts in order for testing
  scripts/run-all-contracts.sh
Labels: enhancement
